server:
#  address: 10.34.2.28
  port: 9992
spring:
  datasource:
    url: jdbc:mysql://192.168.147.192:3306/pintuan?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: pintuan
    password: FJAOFbhS0sMzyZzY



#swagger
swagger:
  title: demo
  description: demo接口文档
  version: 1.0



#日志配置
#logging:
#  config: classpath:logback.xml

#全局异常处理
ratel:
  exception:
    '1000': 系统异常
